language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt coverage test coverageReport

after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash) -t 7253621e-d127-42ff-a863-9c3b4082576e