language: scala
script:
  - sbt coverage "++$TRAVIS_SCALA_VERSION clean" "++$TRAVIS_SCALA_VERSION test" "++$TRAVIS_SCALA_VERSION coverageReport" \

after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)